" Set up leader keys for mappings
let mapleader = "\\"
let maplocalleader = "_"

" Set up shortcuts for editing my vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

if has("mouse")
    set mouse=a
endif

if &t_Co > 2 || has("gui_running")
    syntax on
endif

if has("autocmd")
    filetype plugin indent on
    augroup vimrcEx
        au!
	autocmd FileType text setlocal textwidth=78
	autocmd BufReadPost *
	    \ if line("'\"") > 1 && line("'\"") <= line("$") |
	    \     exe "normal! g`\"" |
	    \ endif
    augroup END
else
    set autoindent
endif

if has("gui_running")
    colorscheme monotone
    set guifont=Fira_Code:h20:cANSI:qDRAFT

    if has("gui_win32")
        " This enables rendering of ligatures for fonts that
        " support that.
        " See: https://github.com/tonsky/FiraCode/issues/462
        set renderoptions=type:directx
    endif

endif

set nocompatible
set backspace=indent,eol,start
set history=50
set ruler

set encoding=utf-8
set scrolloff=3
set sidescrolloff=3
set showmode
set showcmd
set visualbell
" set cursorline
" set cursorcolumn
set relativenumber
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set guioptions-=T
set foldmethod=manual

augroup numbering
    autocmd!
    autocmd InsertEnter * set norelativenumber
    autocmd InsertLeave * set relativenumber
augroup END

nnoremap / /\v
vnoremap / /\v
nnoremap <leader>\ :noh<CR>
set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch
set iskeyword=@,48-57,_,192-255,-

nnoremap <leader>l :bn<CR>
nnoremap <leader>h :bp<CR>
nnoremap <leader><space> :ls<CR>

set background=dark

set nowrap
set colorcolumn=80

set laststatus=2

set fileformat=unix
set fileformats=unix,dos

" Invisible characters (:set list)
set listchars=space:␣,eol:↓,tab:→—,trail:·,precedes:«,extends:»

set swapfile
set directory^=~/vimfiles/swap//

set writebackup
set backup
set backupcopy=auto
set backupdir^=~/vimfiles/backup//

set undofile
set undodir^=~/vimfiles/undo//

set viewdir=~/vimfiles/view

set wildchar=<Tab> wildmenu wildmode=full
set wildcharm=<C-Z>
nnoremap <F10> :b <C-Z>

au BufNewFile,BufRead *.tpl set filetype=php

if has("win32") || has("gui_win32")
    if executable("PowerShell")
        set shell=PowerShell
        set shellcmdflag=-NoProfile\ -NoLogo\ -ExecutionPolicy\ RemoteSigned\ -Command
        set shellquote=\"
        set shellxquote=\ 
    endif
endif

let g:ctrlp_working_path_mode=''

if executable('rg')
    set grepprg=rg\ --vimgrep\ --no-heading
    set grepformat=%f:%l%c:%m,%f:%l:%m
    let g:ctrlp_user_command='rg --files --color=never %s'
    let g:ctrlp_use_caching=0
endif

" Main statusline
set statusline=%<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P

" Syntastic status
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list=1
let g:syntastic_auto_loc_list=1
let g:syntastic_check_on_open=0
let g:syntastic_check_on_wq=0

let g:syntastic_php_checkers=['php', 'phpcs']

" Markdown support
augroup markdown_support
    autocmd!
    autocmd FileType markdown onoremap ih :<c-u>execute "normal! ?^[=-][=-]\\+$\r:nohlsearch\rkvg_"<cr>
    autocmd FileType markdown onoremap ah :<c-u>execute "normal! ?^[=-][=-]\\+$\r:nohlsearch\rg_vk0"<cr>
augroup END

